version: '3'

services:
  mysql:
    image: mysql:8.0
    restart: "no"
    command: "--default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0"
    healthcheck:
      test: "/etc/init.d/mysql status"
      timeout: 1s
      retries: 60
    volumes:
      - "./docker/db/mysql:/var/lib/mysql"
    ports:
      - 3346:3306
    environment:
      MYSQL_DATABASE: eunnow_site
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_USER: eunnow_user
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  php:
    env_file:
      - .env.prod.local
      - .env.prod
    environment:
      APP_ENV: prod
      SYMFONY_ENV: prod
      PHP_INI_MEMORY_LIMIT: 512M
      TEMPLATE_PHP_INI: production
    networks:
      - default
    labels:
      - "traefik.enable=false"
    volumes:
      - "./docker/apache/production.conf:/etc/apache2/sites-enabled/000-default.conf"
    restart: unless-stopped

  server_web:
    networks:
      - default
      - web
    volumes:
      - "./docker/apache/production.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:ro"
    restart: unless-stopped

networks:
  web:
    external:
      name: web
  default: ~
#  TODO: Revoir la config pour la prod
